# Generated by Django 4.2.17 on 2024-12-18 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("user_name", models.TextField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("ORDER", "ORDER"),
                            ("ORDERLINE", "ORDERLINE"),
                            ("SUPPLIER", "SUPPLIER"),
                            ("PAYMENT", "PAYMENT"),
                            ("STOCK", "STOCK"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("title", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThreadParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.thread",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="chat_thread_entity__94d7b7_idx",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.thread",
            ),
        ),
    ]
