# Generated by Django 4.2.17 on 2024-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("ORDERLINE", "Order Line"),
                    ("SUPPLIER", "Supplier"),
                    ("PAYMENT", "Payment"),
                    ("STOCK", "Stock Item"),
                ],
                max_length=50,
            ),
        ),
    ]
