# Generated by Django 4.2.17 on 2024-12-18 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_thread_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="entity_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
