# Generated by Django 4.2.17 on 2024-12-18 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_thread_entity_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("user_id", "user_name"), name="unique_user_id_user_name"
            ),
        ),
    ]
