# Generated by Django 4.2.17 on 2024-12-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message", name="unique_user_id_user_name",
        ),
        migrations.RemoveField(model_name="message", name="user_id",),
        migrations.RemoveField(model_name="message", name="user_name",),
        migrations.AddField(
            model_name="message",
            name="participant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.threadparticipant",
            ),
        ),
        migrations.AddField(
            model_name="threadparticipant",
            name="user_name",
            field=models.TextField(default="Anonymous"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("participant",), name="unique_participant_message"
            ),
        ),
    ]
