# Generated by Django 4.2.17 on 2024-12-19 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_message_unique_user_id_user_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message", name="unique_participant_message",
        ),
        migrations.AlterField(
            model_name="threadparticipant",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
